server:
  port: 8089
  servlet:
    context-path: /lr
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gz-cynosdbmysql-grp-lqdbgset.sql.tencentcdb.com:23453/ruoyi?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: Du061224
#  web:
#    resources:
#      static-locations:
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.djc.entity
